'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import styles from './builder.module.css';
import { Button } from '@/components/shared/Button';
import { Input } from '@/components/shared/Input';
import { Select } from '@/components/shared/Select';

const types=['dca','payment','yield','rebalance'] as const;
const titles={dca:'Dollar-cost averaging',payment:'Autonomous payment',yield:'Yield monitor',rebalance:'Allocation rebalance'};
const workflows={dca:['Schedule','Check balance','Policy threshold','Risk assessment','Execute allocation','Seal proof'],payment:['Schedule','Check balance','Validate recipient','Risk assessment','Send payment','Seal proof'],yield:['Schedule','Read position','Read rewards','Threshold policy','Report state','Seal proof'],rebalance:['Schedule','Read native','Read token','Calculate drift','Report allocation','Seal proof']};

export function StrategyBuilder(){
  const router=useRouter();const[step,setStep]=useState(1);const[type,setType]=useState<(typeof types)[number]>('payment');const[error,setError]=useState('');const[busy,setBusy]=useState(false);
  const[form,setForm]=useState({name:'',chainId:'84532',interval:'hourly',amount:'0',recipientAddress:'0x7a7a831b89a46ddf528780f4a07d17576bef2b4e',senderAddress:'0x7a7a831b89a46ddf528780f4a07d17576bef2b4e',tokenAddress:'',protocol:'Aave',positionAddress:'0x7a7a831b89a46ddf528780f4a07d17576bef2b4e'});const set=(key:string,value:string)=>setForm(v=>({...v,[key]:value}));
  async function submit(){setBusy(true);setError('');const config:any={chainId:Number(form.chainId),interval:form.interval,amount:form.amount,senderAddress:form.senderAddress,recipientAddress:form.recipientAddress};if(form.tokenAddress)config.tokenAddress=form.tokenAddress;if(type==='dca'){config.targetToken=form.tokenAddress||'0x036CbD53842c5426634e7929541eC2318f3dCF7e';config.slippageTolerance=1}if(type==='yield'){config.protocol=form.protocol;config.positionAddress=form.positionAddress;config.harvestThreshold='0';config.tokenAddress=form.tokenAddress||'0x036CbD53842c5426634e7929541eC2318f3dCF7e';config.batchReads=[{contractAddress:config.tokenAddress,abi:[{inputs:[{name:'account',type:'address'}],name:'balanceOf',outputs:[{name:'',type:'uint256'}],stateMutability:'view',type:'function'}],functionName:'balanceOf',functionArgs:[form.positionAddress]}]}if(type==='rebalance'){config.allocations=[{token:'0x036CbD53842c5426634e7929541eC2318f3dCF7e',targetPercent:40},{token:'0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238',targetPercent:60}];config.driftThreshold=5}const response=await fetch('/api/strategies',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:form.name,type,config})});const data=await response.json();if(!response.ok){setError(data.error||'Unable to create strategy');setBusy(false);return}router.push(`/strategies/${data.strategy.id}`);router.refresh()}
  return <section className={styles.studio}>
    <div className={styles.progress}>{['Mandate','Configuration','Review'].map((label,index)=><button type="button" className={step===index+1?styles.current:''} onClick={()=>index+1<step&&setStep(index+1)} key={label}><span>0{index+1}</span>{label}</button>)}</div>
    <div className={styles.columns}>
      <div className={styles.configure}><p className={styles.eyebrow}>Strategy / {titles[type]}</p>{step===1&&<><h2>Choose the operating mandate.</h2><div className={styles.typeList}>{types.map((item,index)=><button type="button" className={type===item?styles.selectedType:''} onClick={()=>setType(item)} key={item}><span>0{index+1}</span><strong>{titles[item]}</strong><small>{item}</small></button>)}</div><Button onClick={()=>setStep(2)}>Configure mandate</Button></>}{step===2&&<><h2>Define the policy boundary.</h2><div className={styles.fields}><Input label="Strategy name" value={form.name} onChange={e=>set('name',e.target.value)} required/><Select label="Network" value={form.chainId} onChange={e=>set('chainId',e.target.value)}><option value="84532">Base Sepolia</option><option value="11155111">Ethereum Sepolia</option></Select><Select label="Interval" value={form.interval} onChange={e=>set('interval',e.target.value)}><option value="hourly">Hourly</option><option value="daily">Daily</option><option value="weekly">Weekly</option></Select><Input label="Amount" value={form.amount} onChange={e=>set('amount',e.target.value)}/><Input label="Sender address" value={form.senderAddress} onChange={e=>set('senderAddress',e.target.value)}/>{type!=='yield'&&<Input label="Recipient address" value={form.recipientAddress} onChange={e=>set('recipientAddress',e.target.value)}/>}<Input label="Token address (optional)" value={form.tokenAddress} onChange={e=>set('tokenAddress',e.target.value)}/>{type==='yield'&&<><Input label="Protocol" value={form.protocol} onChange={e=>set('protocol',e.target.value)}/><Input label="Position address" value={form.positionAddress} onChange={e=>set('positionAddress',e.target.value)}/></>}</div><div className={styles.toolbar}><Button variant="secondary" onClick={()=>setStep(1)}>Back</Button><Button onClick={()=>setStep(3)} disabled={form.name.trim().length<3}>Review policy</Button></div></>}{step===3&&<><h2>Seal the deterministic strategy.</h2><div className={styles.review}><span>Name</span><strong>{form.name}</strong><span>Mandate</span><strong>{titles[type]}</strong><span>Schedule</span><strong>{form.interval}</strong><span>Network</span><strong>{form.chainId==='84532'?'Base Sepolia':'Ethereum Sepolia'}</strong></div><div className={styles.toolbar}><Button variant="secondary" onClick={()=>setStep(2)}>Back</Button><Button onClick={submit} disabled={busy}>{busy?'Sealing…':'Seal strategy'}</Button></div>{error&&<p className={styles.error} role="alert">{error}</p>}</>}</div>
      <div className={styles.workflow}><div className={styles.darkLabel}><span>Workflow / Live preview</span><strong>{titles[type]}</strong></div><div className={styles.nodes}>{workflows[type].map((node,index)=><div className={index===Math.min(step+1,5)?styles.activeNode:''} key={node}><span>{String(index+1).padStart(2,'0')}</span><strong>{node}</strong>{index<workflows[type].length-1&&<i/>}</div>)}</div><p>Configuration changes update the real composition model used when this strategy is persisted.</p></div>
      <aside className={styles.safety}><p className={styles.eyebrow}>Safeguards / Policy</p><h3>Autonomous,<br/>not uncontrolled.</h3><dl><div><dt>Network</dt><dd>Testnet only</dd></div><div><dt>Simulation</dt><dd>Required before write</dd></div><div><dt>Amount cap</dt><dd>0.1 native max</dd></div><div><dt>Risk source</dt><dd>Deterministic local</dd></div><div><dt>Execution</dt><dd>KeeperHub only</dd></div><div><dt>Audit</dt><dd>SHA-256 linked</dd></div></dl><div className={styles.readiness}><span/><strong>{step===3?'Ready to seal':'Configuration in progress'}</strong></div></aside>
    </div>
  </section>
}
