import { notFound } from 'next/navigation';
import styles from '../../pages.module.css';
import { getStrategy } from '@/lib/store/strategies';
import { composeStrategyWorkflow } from '@/lib/strategies/composer';
import { Badge } from '@/components/shared/Badge';
import { AddressDisplay } from '@/components/shared/AddressDisplay';
import { StrategyActions } from '@/components/strategies/StrategyActions';
export const dynamic='force-dynamic';
export default async function StrategyDetail({params}:{params:{id:string}}){const strategy=await getStrategy(params.id);if(!strategy)notFound();const graph=composeStrategyWorkflow(strategy);return <div className={styles.shell}><header className={styles.header}><div><p className={styles.eyebrow}>{strategy.type} mandate / {strategy.id.slice(0,8)}</p><h1>{strategy.name}</h1><p>{strategy.description||'A deterministic Meridian strategy composed for guarded execution.'}</p></div><div><Badge tone={strategy.status==='active'?'success':strategy.status==='error'?'error':'warning'}>{strategy.status}</Badge></div></header><div className={styles.detailGrid}><section className={styles.panel}><p className={styles.eyebrow}>01 / Policy</p><h2>Execution terms</h2><dl><div className={styles.definition}><dt>Chain</dt><dd className={styles.mono}>{strategy.config.chainId}</dd></div><div className={styles.definition}><dt>Interval</dt><dd>{strategy.config.interval}</dd></div><div className={styles.definition}><dt>Amount</dt><dd className={styles.mono}>{strategy.config.amount}</dd></div>{strategy.config.recipientAddress&&<div className={styles.definition}><dt>Recipient</dt><dd><AddressDisplay address={strategy.config.recipientAddress}/></dd></div>}<div className={styles.definition}><dt>Executions</dt><dd>{strategy.executionCount}</dd></div></dl></section><section className={styles.panel}><p className={styles.eyebrow}>02 / KeeperHub proof</p><h2>Infrastructure state</h2><dl><div className={styles.definition}><dt>Workflow ID</dt><dd className={styles.mono}>{strategy.keeperHubWorkflowId||'Not created'}</dd></div><div className={styles.definition}><dt>Marketplace</dt><dd className={styles.mono}>{strategy.marketplaceSlug||'Not listed'}</dd></div><div className={styles.definition}><dt>Last execution</dt><dd>{strategy.lastExecutionAt?new Date(strategy.lastExecutionAt).toLocaleString():'Awaiting first execution'}</dd></div></dl><StrategyActions strategy={strategy}/></section></div><section className={styles.graphSection}><p className={styles.eyebrow}>FIG. 02 / Workflow composition</p><div className={styles.graph}>{graph.nodes.map((node,index)=><div key={node.id} style={{display:'contents'}}><div className={styles.node}><small>{String(index+1).padStart(2,'0')} / {node.type}</small><strong>{node.data.label}</strong><div className={styles.mono}>{String(node.data.config.actionType||node.data.config.triggerType)}</div></div>{index<graph.nodes.length-1&&<span className={styles.arrow}>→</span>}</div>)}</div></section></div>}
